import { NAV_ITEM_TYPE_ITEM, NAV_ITEM_TYPE_TITLE } from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { PERMISSIONS } from '@/utils/permissions'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: Object.values(PERMISSIONS),
        subMenu: [
            {
                key: 'dashboard1',
                path: '/dashboard',
                title: 'Dashboard',
                translateKey: 'Dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: Object.values(PERMISSIONS),
                subMenu: [],
            },
        ],
    },
    {
        key: 'forms',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [PERMISSIONS.MANAGE_RFQ, PERMISSIONS.MANAGE_PO],
        subMenu: [
            {
                key: 'forms.rfq',
                path: '/rfq',
                title: 'Generate RFQ',
                translateKey: 'Generate RFQ',
                icon: 'forms',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.MANAGE_RFQ],
                subMenu: [],
            },
            {
                key: 'forms.purchase-order',
                path: '/purchase-order',
                title: 'Purchase Order',
                translateKey: 'Purchase Order',
                icon: 'po',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.MANAGE_PO],
                subMenu: [],
            },
        ],
    },
    {
        key: 'reports',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [PERMISSIONS.MANAGE_RFQ, PERMISSIONS.MANAGE_CS, PERMISSIONS.MANAGE_PO, PERMISSIONS.VIEW_QUOTATION, PERMISSIONS.VENDOR_ACCESS],
        subMenu: [
            {
                key: 'reports.rfqs',
                path: '/rfqs',
                title: 'RFQ Report',
                translateKey: 'RFQ Report',
                icon: 'reports',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.MANAGE_RFQ, PERMISSIONS.VENDOR_ACCESS],
                subMenu: [],
            },
            {
                key: 'reports.quotations',
                path: '/quotations',
                title: 'Quotations',
                translateKey: 'Quotations',
                icon: 'qs',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.VIEW_QUOTATION, PERMISSIONS.VENDOR_ACCESS],
                subMenu: [],
            },
            {
                key: 'reports.comparative-statements',
                path: '/comparative-statements',
                title: 'Comparative Statements',
                translateKey: 'Comparative Statements',
                icon: 'cs',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.MANAGE_CS],
                subMenu: [],
            },
            {
                key: 'reports.purchase-orders',
                path: '/purchase-orders',
                title: 'PO Report',
                translateKey: 'PO Report',
                icon: 'pos',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.MANAGE_PO, PERMISSIONS.VENDOR_ACCESS],
                subMenu: [],
            },
            // {
            //     key: 'reports.advance-payments',
            //     path: '/advance-payments',
            //     title: 'Advance Payments',
            //     translateKey: 'Advance Payments',
            //     icon: 'cash',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [PERMISSIONS.VIEW_INDENT_REGISTER],
            //     subMenu: [],
            // },
            {
                key: 'reports.indent-register',
                path: '/indent-register',
                title: 'Indent Register',
                translateKey: 'Indent Register',
                icon: 'indents',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [PERMISSIONS.VIEW_INDENT_REGISTER],
                subMenu: [],
            },
        ],
    },
    {
        key: 'security.master-control',
        path: '/master-control',
        title: 'Master Control',
        translateKey: 'Master Control',
        icon: 'masters',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PERMISSIONS.MASTER_CONTROL],
        subMenu: [],
    },
    {
        key: 'security.access-control',
        path: '/access-control',
        title: 'Access Control',
        translateKey: 'Access Control',
        icon: 'ac',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PERMISSIONS.ACCESS_CONTROL],
        subMenu: [],
    },
        {
        key: 'security.approve-vendor',
        path: '/approve-vendor',
        title: 'Approve Vendor',
        translateKey: 'Approve Vendor',
        icon: 'approve',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PERMISSIONS.APPROVE_VENDOR],
        subMenu: [],
    },
]

export default navigationConfig
